# Generated by Django 5.2.6 on 2025-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
