# Generated by Django 5.2.6 on 2025-09-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0002_rename_cliniccenter_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARVAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arv_availability', models.CharField(choices=[('available', 'Available'), ('not available', 'Not available')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.center')),
            ],
        ),
    ]
