# Generated by Django 5.2.6 on 2025-09-06 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCenter',
            fields=[
                ('center_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
                ('center_type', models.CharField(choices=[('clinic', 'Clinic'), ('counseling_center', 'Counseling Center')], max_length=100)),
                ('image_path', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_number', models.CharField(max_length=20)),
                ('operational_status', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_hours', models.DateTimeField()),
            ],
        ),
    ]
