# Generated by Django 5.2.6 on 2025-09-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicCenter',
            new_name='Center',
        ),
    ]
